openapi: 3.0.1
info:
  title: Shownotes
  description: Get transcript from Shownotes app
  version: 'v1'
servers:
  - url: https://cooper.app.n8n.cloud/webhook/6f7b288e-1efe-4504-a6fd-660931327269
paths:
  //{show}:
    get:
      operationId: getShows
      summary: Get the transcript
      parameters:
      - in: path
        name: show
        schema:
            type: string
        required: true
        description: The show name
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getShowResponse'

components:
  schemas:
    getShowResponse:
      type: object
      properties:
        todos:
          type: array
          items:
            type: string
          description: The list of transcripts.
